..\..\..\build\modules\console\Release\rmvm.exe performance 2>err.json
..\..\..\build\modules\console\Release\rmvm.exe performance 2>err.json
..\..\..\build\modules\console\Release\rmvm.exe performance 2>err.json
..\..\..\build\modules\console\Release\rmvm.exe performance 2>err.json
..\..\..\build\modules\console\Release\rmvm.exe performance 2>err.json
..\..\..\build\modules\console\Release\rmvm.exe performance 2>err.json
..\..\..\build\modules\console\Release\rmvm.exe performance 2>err.json
..\..\..\build\modules\console\Release\rmvm.exe performance 2>err.json
..\..\..\build\modules\console\Release\rmvm.exe performance 2>err.json
..\..\..\build\modules\console\Release\rmvm.exe performance 2>err.json
