..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
..\..\..\build\src\trmvm\Release\trmvm.exe performance.json 2>err.json 1>>after.txt
