var searchData=
[
  ['обзор_0',['Обзор',['../md_analysis.html#autotoc_md178',1,'']]],
  ['обзор_20jsonrvm_20c_2017_1',['1.1 Обзор jsonRVM (C++17)',['../md_migration-analysis.html#autotoc_md217',1,'']]],
  ['обоснование_2',['обоснование',['../md_plan.html#autotoc_md283',1,'Обоснование'],['../md_plan.html#autotoc_md279',1,'Обоснование'],['../md_plan.html#autotoc_md275',1,'Обоснование'],['../md_plan.html#autotoc_md271',1,'Обоснование'],['../md_plan.html#autotoc_md267',1,'Обоснование'],['../md_plan.html#autotoc_md263',1,'Обоснование'],['../md_plan.html#autotoc_md259',1,'Обоснование']]],
  ['обработка_20исключений_3',['2.3. Обработка исключений',['../md_analysis.html#autotoc_md189',1,'']]],
  ['образование_20и_20обучение_20программированию_4',['Направление 2: Образование и обучение программированию',['../md_plan.html#autotoc_md262',1,'']]],
  ['обучение_20программированию_5',['Направление 2: Образование и обучение программированию',['../md_plan.html#autotoc_md262',1,'']]],
  ['общепринятых_20терминов_6',['Словарь общепринятых терминов',['../md_doc_2wiki__concepts.html',1,'']]],
  ['объекта_7',['Сущность объекта',['../md_doc_2_dictionary.html#autotoc_md46',1,'']]],
  ['объекта_20описывающего_20сущность_8',['Семантика значений разных типов в полях $sub, $rel, $obj json объекта описывающего сущность',['../md_doc_2_r_v_m.html#autotoc_md155',1,'']]],
  ['объективация_20сущности_9',['Объективация сущности',['../md_doc_2_dictionary.html#objectification',1,'']]],
  ['объектов_20модели_20отношений_10',['Множество кортежей - объектов Модели Отношений',['../md_doc_2_mathematical__definition.html#autotoc_md80',1,'']]],
  ['объект_11',['объект',['../md_doc_2_dictionary.html#ctx_obj',1,'Контекстный объект'],['../md_doc_2_dictionary.html#obj',1,'Объект']]],
  ['объект_20отношения_12',['Объект отношения',['../md_doc_2_dictionary.html#rel_obj',1,'']]],
  ['об_20эквивалентности_20представлений_13',['3.1. Теорема об эквивалентности представлений',['../md_doc_2relations-model-ru.html#autotoc_md126',1,'']]],
  ['ограничения_14',['ограничения',['../md_analysis.html#autotoc_md196',1,'1. Архитектурные ограничения'],['../md_analysis.html#autotoc_md200',1,'2. Функциональные ограничения']]],
  ['ограниченная_20глубина_20контекста_15',['1.2. Ограниченная глубина контекста',['../md_analysis.html#autotoc_md198',1,'']]],
  ['ограниченная_20работа_20со_20строками_16',['2.2. Ограниченная работа со строками',['../md_analysis.html#autotoc_md202',1,'']]],
  ['ооп_17',['Привести аналогию с ООП',['../md_doc_2_introduction.html#autotoc_md65',1,'']]],
  ['описание_18',['Описание',['../md__r_e_a_d_m_e.html#autotoc_md298',1,'']]],
  ['описание_20модели_20отношений_19',['Математическое описание Модели Отношений',['../md_doc_2relations-model-ru.html',1,'']]],
  ['описывающего_20сущность_20',['Семантика значений разных типов в полях $sub, $rel, $obj json объекта описывающего сущность',['../md_doc_2_r_v_m.html#autotoc_md155',1,'']]],
  ['определение_20из_20теории_20связей_21',['4.1. Определение из Теории связей',['../md_doc_2relations-model-ru.html#autotoc_md129',1,'']]],
  ['определение_20триединой_20сущности_22',['5.1. Определение триединой сущности',['../md_doc_2relations-model-ru.html#autotoc_md133',1,'']]],
  ['определения_23',['1. Базовые определения',['../md_doc_2relations-model-ru.html#autotoc_md118',1,'']]],
  ['оптимизации_20производительности_24',['Оптимизации производительности',['../md__advantages_01and_01benefits_01of_01the_01json_r_v_m_01project.html#autotoc_md168',1,'']]],
  ['оптимизаций_25',['1.3. Отсутствие оптимизаций',['../md_analysis.html#autotoc_md199',1,'']]],
  ['оптимизация_26',['Направление 4: Производительность и оптимизация',['../md_plan.html#autotoc_md270',1,'']]],
  ['основная_20рекомендация_3a_20go_20wasm_20tinygo_20для_20web_20gui_27',['5.1 Основная рекомендация: Go + WASM (TinyGo) для Web GUI',['../md_migration-analysis.html#autotoc_md241',1,'']]],
  ['основные_20концепции_28',['Основные концепции',['../md__r_e_a_d_m_e.html#autotoc_md299',1,'']]],
  ['основы_29',['Архитектурные преимущества и концептуальные основы',['../md__advantages_01and_01benefits_01of_01the_01json_r_v_m_01project.html#autotoc_md163',1,'']]],
  ['особенности_30',['Ключевые особенности',['../md__r_e_a_d_m_e.html#autotoc_md300',1,'']]],
  ['отношение_31',['отношение',['../md_doc_2_dictionary.html#ctx_rel',1,'Контекстное отношение'],['../md_doc_2_dictionary.html#rel',1,'Отношение']]],
  ['отношение_20сущности_32',['Отношение сущности',['../md_doc_2_dictionary.html#ent_rel',1,'']]],
  ['отношений_33',['отношений',['../md_doc_2_dictionary.html#autotoc_md21',1,'Ассоциативная Модель Отношений'],['../md_doc_2_dictionary.html#rm_root',1,'Корень модели отношений'],['../md_doc_2_dictionary.html#root_ent',1,'Корневая сущность модели отношений'],['../md_doc_2relations-model-ru.html',1,'Математическое описание Модели Отношений'],['../md_doc_2_mathematical__definition.html#autotoc_md80',1,'Множество кортежей - объектов Модели Отношений'],['../md_doc_2_mathematical__definition.html#autotoc_md81',1,'Множество кортежей - отношений Модели Отношений'],['../md_doc_2_mathematical__definition.html#autotoc_md82',1,'Множество кортежей - субъектов Модели Отношений'],['../md_doc_2_mathematical__definition.html#autotoc_md79',1,'Множество кортежей - сущностей Модели Отношений'],['../md_doc_2_r_m.html',1,'Модель Отношений'],['../md_doc_2_dictionary.html#autotoc_md22',1,'Модель Отношений'],['../md_doc_2_dictionary.html#rm',1,'Модель Отношений'],['../md__advantages_01and_01benefits_01of_01the_01json_r_v_m_01project.html#autotoc_md162',1,'Преимущества и польза проекта jsonRVM: Анализ виртуальной машины модели отношений'],['../md__advantages_01and_01benefits_01of_01the_01json_r_v_m_01project.html#autotoc_md165',1,'Система сущностей и отношений'],['../md_doc_2relations-model-ru.html#autotoc_md135',1,'6. Свойства Модели Отношений']]],
  ['отношений_20как_20функция_34',['отношений как функция',['../md_doc_2relations-model-ru.html#autotoc_md128',1,'4. Модель Отношений как функция'],['../md_doc_2relations-model-ru.html#autotoc_md130',1,'4.2. Модель Отношений как функция']]],
  ['отношений_20модели_20отношений_35',['Множество кортежей - отношений Модели Отношений',['../md_doc_2_mathematical__definition.html#autotoc_md81',1,'']]],
  ['отношений_20старый_20текст_36',['Модель Отношений (старый текст)',['../md_doc_2rmodel.html',1,'']]],
  ['отношений_20формата_20json_37',['Ассоциативаня Модель Отношений формата json',['../md_doc_2json__definition.html',1,'']]],
  ['отношений_20это_20язык_20метапрограммирования_38',['Модель Отношений - это язык метапрограммирования.',['../md_doc_2_introduction.html#autotoc_md64',1,'']]],
  ['отношения_39',['отношения',['../md_doc_2_dictionary.html#outter_rel_struct',1,'Внешняя структура отношения'],['../md_doc_2_dictionary.html#inner_ent_struct',1,'Внутренняя структура отношения'],['../md_doc_2_dictionary.html#rel_res',1,'Значение отношения'],['../md_doc_2_dictionary.html#rel_obj',1,'Объект отношения'],['../md_doc_2_dictionary.html#parent_ctx',1,'Родительский контекст отношения'],['../md_doc_2_dictionary.html#rel_struct',1,'Структура отношения'],['../md_doc_2_dictionary.html#ent_view',1,'Субъективация отношения'],['../md_doc_2_dictionary.html#rel_sub',1,'Субъект отношения'],['../md_doc_2_dictionary.html#rel_ent',1,'Сущность отношения'],['../md_doc_2_dictionary.html#clar_state',1,'Clarification of the state of the relation / Выяснение состояния отношения'],['../md_doc_2json__definition.html#autotoc_md67',1,'rel - ассоциация типа отношения'],['../md_doc_2_dictionary.html#rel_clar',1,'Relation clarification / Выяснение отношения']]],
  ['отсутствие_20оптимизаций_40',['1.3. Отсутствие оптимизаций',['../md_analysis.html#autotoc_md199',1,'']]],
  ['отсутствующие_20возможности_41',['2.3. Отсутствующие возможности',['../md_analysis.html#autotoc_md203',1,'']]],
  ['от_20старой_20проекции_20мо_20в_20json_20к_20ассоциативной_20проекции_20в_20json_42',['идеи по переходу от старой проекции МО в json к ассоциативной проекции в json',['../md_doc_2json__definition.html#autotoc_md74',1,'']]],
  ['оценка_20для_20jhub_43',['оценка для jhub',['../md_migration-analysis.html#autotoc_md226',1,'3.1.3 Оценка для jhub'],['../md_migration-analysis.html#autotoc_md231',1,'3.2.3 Оценка для jhub']]],
  ['оценка_20wasm_20как_20самостоятельного_20подхода_44',['3.3.3 Оценка WASM как самостоятельного подхода',['../md_migration-analysis.html#autotoc_md236',1,'']]],
  ['о_45',['О',['../md_doc_2_dictionary.html#autotoc_md41',1,'']]],
  ['о_20свойствах_20атрибутах_20и_20элементах_20сущности_3a_46',['О свойствах (атрибутах) и элементах сущности:',['../md_doc_2_r_v_m.html#autotoc_md154',1,'']]]
];
