var searchData=
[
  ['данных_0',['данных',['../md_doc_2_dictionary.html#amd',1,'Ассоциативная Модель Данных'],['../md__advantages_01and_01benefits_01of_01the_01json_r_v_m_01project.html#autotoc_md173',1,'ORM-системы и управление базами данных']]],
  ['два_20аспекта_20сущности_1',['2.1. Два аспекта сущности',['../md_doc_2relations-model-ru.html#autotoc_md123',1,'']]],
  ['двумерной_20асети_2',['4.3. Сведение к двумерной асети',['../md_doc_2relations-model-ru.html#autotoc_md131',1,'']]],
  ['декларативная_20парадигма_20программирования_3',['Декларативная парадигма программирования',['../md__advantages_01and_01benefits_01of_01the_01json_r_v_m_01project.html#autotoc_md164',1,'']]],
  ['декларативный_20подход_4',['1.1. Декларативный подход',['../md_analysis.html#autotoc_md182',1,'']]],
  ['длины_202_5',['МО в теории множеств как множество взаимосвязанных множеств кортежей длины 2',['../md_doc_2_mathematical__definition.html#autotoc_md83',1,'']]],
  ['длины_203_20к_204м_20множествам_20кортежей_20длины_202_3a_6',['Преобразование 4х множеств кортежей длины 3 к 4м множествам кортежей длины 2:',['../md_doc_2_mathematical__definition.html#autotoc_md77',1,'']]],
  ['для_20c_20emscripten_7',['3.3.1 WASM как дополнительный таргет для C++ (Emscripten)',['../md_migration-analysis.html#autotoc_md234',1,'']]],
  ['для_20jhub_8',['для jhub',['../md_migration-analysis.html#autotoc_md226',1,'3.1.3 Оценка для jhub'],['../md_migration-analysis.html#autotoc_md231',1,'3.2.3 Оценка для jhub']]],
  ['для_20production_20critical_20компонентов_9',['5.2 Альтернативная рекомендация: Rust для Production Critical компонентов',['../md_migration-analysis.html#autotoc_md242',1,'']]],
  ['для_20web_20gui_10',['5.1 Основная рекомендация: Go + WASM (TinyGo) для Web GUI',['../md_migration-analysis.html#autotoc_md241',1,'']]],
  ['доказательство_20эквивалентности_11',['3.2. Доказательство эквивалентности',['../md_doc_2relations-model-ru.html#autotoc_md127',1,'']]],
  ['документация_12',['3.3. Документация',['../md_analysis.html#autotoc_md207',1,'']]],
  ['документация_20documentation_13',['Документация / Documentation',['../md__r_e_a_d_m_e.html#autotoc_md311',1,'']]],
  ['документация_20technical_20documentation_14',['Техническая документация / Technical Documentation',['../md__r_e_a_d_m_e.html#autotoc_md313',1,'']]],
  ['долгосрочная_20перспектива_15',['Фаза 4: Масштабирование (долгосрочная перспектива)',['../md_plan.html#autotoc_md290',1,'']]],
  ['дополнение_16',['5.3 WebAssembly — не замена, а дополнение',['../md_migration-analysis.html#autotoc_md243',1,'']]],
  ['дополнительный_20таргет_20для_20c_20emscripten_17',['3.3.1 WASM как дополнительный таргет для C++ (Emscripten)',['../md_migration-analysis.html#autotoc_md234',1,'']]],
  ['дорожная_20карта_18',['Дорожная карта',['../md_plan.html#autotoc_md286',1,'']]],
  ['доступность_19',['Направление 1: Кроссплатформенность и доступность',['../md_plan.html#autotoc_md258',1,'']]],
  ['доступность_20следующий_20этап_20',['Фаза 2: Доступность (следующий этап)',['../md_plan.html#autotoc_md288',1,'']]],
  ['дочерний_20контекст_20исполнения_21',['Дочерний контекст исполнения',['../md_doc_2_dictionary.html#child_ctx',1,'']]],
  ['дуплетам_22',['3. Сведение триплетов к дуплетам',['../md_doc_2relations-model-ru.html#autotoc_md125',1,'']]],
  ['дуплетов_23',['2.2. Типы связей (дуплетов)',['../md_doc_2relations-model-ru.html#autotoc_md124',1,'']]],
  ['дуплеты_24',['1.2. Триплеты и Дуплеты',['../md_doc_2relations-model-ru.html#autotoc_md120',1,'']]],
  ['д_25',['Д',['../md_doc_2_dictionary.html#autotoc_md28',1,'']]]
];
