var searchData=
[
  ['rdf_0',['RDF',['../md_doc_2_abbreviations.html#autotoc_md18',1,'']]],
  ['re_20os_3a_1',['2. Выделяем связи типа SO, ER, RE, OS:',['../md_doc_2_mathematical__definition.html#autotoc_md86',1,'']]],
  ['readme_2',['README',['../md__r_e_a_d_m_e.html',1,'']]],
  ['readme_2emd_3',['README.md',['../_r_e_a_d_m_e_8md.html',1,'']]],
  ['reduction_20of_20triplets_20to_20duplets_4',['3. Reduction of Triplets to Duplets',['../md_doc_2relations-model-en.html#autotoc_md97',1,'']]],
  ['reduction_20to_20two_20dimensional_20associative_20network_5',['4.3. Reduction to Two-Dimensional Associative Network',['../md_doc_2relations-model-en.html#autotoc_md103',1,'']]],
  ['references_6',['references',['../md_doc_2relations-model-en.html#autotoc_md90',1,'1.1. Entity References'],['../md_doc_2relations-model-en.html#autotoc_md117',1,'References']]],
  ['reflexivity_7',['6.2. Reflexivity',['../md_doc_2relations-model-en.html#autotoc_md109',1,'']]],
  ['rel_8',['rel',['../structrm_1_1callctx.html#aba5f90dc8ed8caa3d00594749ca2b085',1,'rm::callctx::rel'],['../structrm_1_1vm__ctx.html#a5d5dfd112b297c6c3de4fabc75e6d26c',1,'rm::vm_ctx::rel']]],
  ['rel_20ассоциация_20типа_20отношения_9',['rel - ассоциация типа отношения',['../md_doc_2json__definition.html#autotoc_md67',1,'']]],
  ['rel_20obj_10',['rel obj',['../md_doc_2_x_d0_x_b_f_x_d0_x_b_b_x_d0_x_b0_x_d0_x_b_d___x_d0_x9_c_x_d0_x9_e.html#autotoc_md5',1,'0. ent = &lt;sub, rel, obj&gt;'],['../md_doc_2_x_d0_x_b_f_x_d0_x_b_b_x_d0_x_b0_x_d0_x_b_d___x_d0_x9_c_x_d0_x9_e.html#autotoc_md7',1,'1. sub =  = { ent, rel, obj }'],['../md_doc_2_x_d0_x_b_f_x_d0_x_b_b_x_d0_x_b0_x_d0_x_b_d___x_d0_x9_c_x_d0_x9_e.html#autotoc_md10',1,'Ent = &lt;Sub, Rel, Obj&gt;']]],
  ['rel_20sub_20ent_20obj_11',['1. rel = { sub, ent, obj }',['../md_doc_2_x_d0_x_b_f_x_d0_x_b_b_x_d0_x_b0_x_d0_x_b_d___x_d0_x9_c_x_d0_x9_e.html#autotoc_md6',1,'']]],
  ['relation_20выяснение_20состояния_20отношения_12',['Clarification of the state of the relation / Выяснение состояния отношения',['../md_doc_2_dictionary.html#clar_state',1,'']]],
  ['relation_20clarification_20выяснение_20отношения_13',['Relation clarification / Выяснение отношения',['../md_doc_2_dictionary.html#rel_clar',1,'']]],
  ['relations_20model_14',['relations model',['../md_doc_2relations-model-en.html#autotoc_md107',1,'6. Properties of the Relations Model'],['../md_doc_2relations-model-en.html',1,'Mathematical Description of the Relations Model']]],
  ['relations_20model_20as_20associative_20network_15',['4. Relations Model as Associative Network',['../md_doc_2relations-model-en.html#autotoc_md100',1,'']]],
  ['relations_20model_20as_20four_20interconnected_20sets_16',['2. Relations Model as Four Interconnected Sets',['../md_doc_2relations-model-en.html#autotoc_md93',1,'']]],
  ['relations_20model_20as_20three_20dimensional_20associative_20network_17',['4.2. Relations Model as Three-Dimensional Associative Network',['../md_doc_2relations-model-en.html#autotoc_md102',1,'']]],
  ['relations_20model_20virtual_20machine_18',['jsonRVM — json Relations (Model) Virtual Machine',['../md__r_e_a_d_m_e.html#autotoc_md256',1,'']]],
  ['relations_2dmodel_2den_2emd_19',['relations-model-en.md',['../relations-model-en_8md.html',1,'']]],
  ['relations_2dmodel_2dru_2emd_20',['relations-model-ru.md',['../relations-model-ru_8md.html',1,'']]],
  ['representation_21',['7. JSON Representation',['../md_doc_2relations-model-en.html#autotoc_md112',1,'']]],
  ['representation_20equivalence_22',['3.1. Theorem on Representation Equivalence',['../md_doc_2relations-model-en.html#autotoc_md98',1,'']]],
  ['representation_20of_20triplet_20as_20nested_20ordered_20pairs_23',['1.3. Representation of Triplet as Nested Ordered Pairs',['../md_doc_2relations-model-en.html#autotoc_md92',1,'']]],
  ['requirements_24',['Требования / Requirements',['../md__r_e_a_d_m_e.html#autotoc_md281',1,'']]],
  ['rm_25',['rm',['../namespacerm.html',1,'']]],
  ['rm_20мо_26',['RM / МО',['../md_doc_2_abbreviations.html#autotoc_md13',1,'']]],
  ['rm_2emd_27',['RM.md',['../_r_m_8md.html',1,'']]],
  ['rmodel_2emd_28',['rmodel.md',['../rmodel_8md.html',1,'']]],
  ['rmvm_5fversion_29',['rmvm_version',['../structrm_1_1vm_1_1rmvm__version.html',1,'rm::vm']]],
  ['running_20tests_30',['Запуск тестов / Running Tests',['../md__r_e_a_d_m_e.html#autotoc_md283',1,'']]],
  ['rvm_31',['rvm',['../structrm_1_1callctx.html#a2dcaadcec0580368a1e8a8d0519f7237',1,'rm::callctx']]],
  ['rvm_20рвм_32',['RVM / РВМ',['../md_doc_2_abbreviations.html#autotoc_md14',1,'']]],
  ['rvm_20_3a_33',['Семантика json значений при исполнении  (json как байткод RVM):',['../md_doc_2_r_v_m.html#autotoc_md160',1,'']]],
  ['rvm_2emd_34',['RVM.md',['../_r_v_m_8md.html',1,'']]]
];
